select
    trim(transaction_id) as transaction_id,
    trim(claim_id) as claim_id,
    trim(charge_id) as charge_id,
    trim(patient_id) as patient_id,
    trim(transaction_type) as transaction_type,
    amount,
    trim(payment_method) as payment_method,
    from_date,
    to_date,
    trim(place_of_service) as place_of_service,
    trim(procedure_code) as procedure_code,
    trim(diagnosis_ref_1) as diagnosis_ref_1,
    trim(diagnosis_ref_2) as diagnosis_ref_2,
    trim(diagnosis_ref_3) as diagnosis_ref_3,
    trim(diagnosis_ref_4) as diagnosis_ref_4,
    units,
    trim(department_id) as department_id,
    unit_amount,
    payments,
    adjustments,
    transfers,
    outstanding,
    trim(appointment_id) as appointment_id,
    trim(patient_insurance_id) as patient_insurance_id,
    trim(provider_id) as provider_id
from {{ source('raw', 'raw_claim_transactions') }}