select
    trim(claim_id) as claim_id,
    trim(patient_id) as patient_id,
    trim(provider_id) as provider_id,
    trim(primary_patient_insurance_id) as primary_patient_insurance_id,
    trim(secondary_patient_insurance_id) as secondary_patient_insurance_id,
    trim(department_id) as department_id,
    trim(patient_department_id) as patient_department_id,
    trim(diagnosis_1) as diagnosis_1,
    trim(diagnosis_2) as diagnosis_2,
    trim(diagnosis_3) as diagnosis_3,
    trim(diagnosis_4) as diagnosis_4,
    trim(appointment_id) as appointment_id,
    current_illness_date,
    service_date,
    trim(status_primary) as status_primary,
    trim(status_secondary) as status_secondary,
    trim(status_patient) as status_patient,
    outstanding_primary,
    outstanding_secondary,
    outstanding_patient,
    last_billed_date_primary,
    last_billed_date_secondary,
    last_billed_date_patient,
    trim(claim_type_id_primary) as claim_type_id_primary,
    trim(claim_type_id_secondary) as claim_type_id_secondary
from {{ source('raw', 'raw_claims') }}